language: node_js
node_js: node
dist: trusty
before_install:
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo add-apt-repository -y ppa:wine/wine-builds
- sudo apt-get update
- sudo apt-get install -y wine-staging devscripts build-essential lintian dh-make rpm yarn
install:
- yarn
before_script:
- export WINEDLLOVERRIDES="mscoree,mshtml="
- export PATH=$PATH:/opt/wine-staging/bin/
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- rm -rf rpmbuild/
- mkdir -p rpmbuild/SOURCES
- tar -cjf rpmbuild/SOURCES/dummy.tar.bz2 readme.md
script:
- npm run build:linux
- debuild -b -uc -us
- npm run build:osx
- npm run build:win
- npm run build:linuxarmv7l
- debuild -b -uc -us -aarmhf
- cd rpmbuild && rpmbuild --define "_topdir $(pwd)/" -bb ../whatsapp-desktop.spec && cd ..
- npm run build:linux32
- npm run build:appimage
before_deploy:
- sudo apt-get install -y zip tar gzip
- cd dist/ && zip -r WhatsApp-win32-x64.zip WhatsApp-win32-x64/ && zip -r WhatsApp-darwin-x64.zip WhatsApp-darwin-x64/ && tar czf WhatsApp-linux-ia32.tar.gz WhatsApp-linux-ia32/ && tar czf WhatsApp-linux-x64.tar.gz WhatsApp-linux-x64/ && tar czf WhatsApp-linux-armv7l.tar.gz WhatsApp-linux-armv7l/ && cd ..
- export RELEASE_AMD64_PKG_FILE=$(ls ../whatsapp-desktop*amd64.deb)
- export RELEASE_ARM_PKG_FILE=$(ls ../whatsapp-desktop*armhf.deb)
- export RELEASE_AMD64_RPM_FILE=$(ls rpmbuild/RPMS/x86_64/*.rpm)
- export RELEASE_APPIMAGE_FILE=$(ls dist/whatsapp-desktop*-x86_64.Appimage)
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
  file_glob: true
  file:
  - dist/WhatsApp-win32-x64.zip
  - dist/WhatsApp-darwin-x64.zip
  - dist/WhatsApp-linux-x64.tar.gz
  - dist/WhatsApp-linux-ia32.tar.gz
  - dist/WhatsApp-linux-armv7l.tar.gz
  - "${RELEASE_AMD64_PKG_FILE}"
  - "${RELEASE_ARM_PKG_FILE}"
  - "${RELEASE_AMD64_RPM_FILE}"
  - "${RELEASE_APPIMAGE_FILE}"
  api_key:
    secure: TX/psfzZ+R8Ua7y/uWUSFLVzajfANM/flNyDO5bG9X/LqURoWOQEnjmvUYV4xBp9IJM/xc5/icvUfl2DyNPunmZdRtVv0M85JhkKkQ0wywGhSHENo33kAWDn9v9gFb5w/cRpkghHOYUH9C7GLSulVxtuyb4FacrvvUdqr6kcth9gzWAqG3MBJNID+sI0/JooyGdu2VTMaszlImyzM4m76UQVl9K09ZCQbtoSlnVGYBhkMbu13gh750LWFbdf02KUkEO3TxQ8WYRMJ1VaXy0j/qcCi3mFAQxWxwvvxDrayNuZPoqLcfp0FFJLtqwT+QIaCPHpWwUWiiAHpLWNj/OmzEk7NkmTkKJ44ToBnJgAs3KibEvS+qrXdUO9qOWYUFG27EkCjQSppSWtZmn9EkY4BilSp6lFL8fPQWcjzvT7tkoQUs//g+cgyYHu5t3fgT3Ld1FuSkbpCzixxwbfWzUnR+jco0aWmtAT6f1wpbHmWAWEUI12SNEy8BtnvyZdXCGIYJFD7vJEM9i8NoT/ztvW1uXq7zqN8IZAFYt6BwmgHSWJ/KKsvaD9itOApVJCWEZy/JH7bm/7iE1z9KjWfUelfIwLAc1VJ5HHtEVfeLdz1oCwQ/WXSPeasQuMPqxrBFgHteyz6zdg1cgY3BoiLMZFpyaafYKdLYpDS9pS7rTuvuM=
